services:

  kafka:
    image: confluentinc/cp-kafka:7.8.3
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_KRAFT_MODE: 'true'
      CLUSTER_ID: '1L6g7nGhU-eAKfL--X25wo'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    volumes:
      - kafka_kraft:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list > /dev/null 2>&1"]      
      interval: 10s
      timeout: 5s
      retries: 5

      

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: identities
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_PASSWORD: israelyarbloom
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD
      interval: 5s
      timeout: 5s
      retries: 10



  adminer:
    image: adminer
    ports:
      - "8080:8080"


  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: israelyarbloom
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "-u", "admin", "-p", "israelyarbloom", "--authenticationDatabase", "admin", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s


  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    mem_limit: 1g



  data_loader:
    build: data_loader/
    container_name: data_loader
    ports:
      - "9900:9900"
    environment:
      KAFKA_URI: kafka:9092
      GPS_PATH: ./data/gps_stream.json
      INTERCEPTS_PATH: ./data/intercepts.json
      IDENTITIES_PATH: ./data/identities.csv
      MYSQL_HOST: mysql
      MYSQL_DATABASE: identities
      MYSQL_USER: app_user
      MYSQL_PASSWORD: israelyarbloom
    volumes:
      - ./data/gps_stream.json:/app/data/gps_stream.json
      - ./data/intercepts.json:/app/data/intercepts.json
      - ./data/identities.csv:/app/data/identities.csv
    depends_on:
      kafka:
        condition: service_healthy
      mysql:
        condition: service_healthy


  data_analyzer:
    build: data_analyzer/
    container_name: data_analyzer
    ports: 
      - 8200:8200
    environment:
      KAFKA_URI: kafka:9092
      MYSQL_HOST: mysql
      MYSQL_DATABASE: identities
      MYSQL_USER: app_user
      MYSQL_PASSWORD: israelyarbloom
      MONGO_URI: mongodb://admin:israelyarbloom@mongo:27017/?authSource=admin
    depends_on:
      - data_loader
      - mongo



  end_user_svc:
    build: end_user_service/
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://admin:israelyarbloom@mongo:27017/?authSource=admin
      ELS_URI: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch


  logger:
    build: logger/
    environment:
      KAFKA_URI: kafka:9092
    depends_on:
      - data_loader
      - data_analyzer
      - end_user_service


volumes:
  kafka_kraft:
  mysql_data:
  mongo_data: