apiVersion: apps/v1

kind: Deployment

metadata:
  name: end-user
  labels:
    app: end-user

spec:
  replicas: 1
  selector:
    matchLabels:
      app: end-user
  template:
    metadata:
      labels:
        app: end-user
    spec:
      containers:
        - name: end-user
          image: israelyarbloom/end_user:latest
          ports:
            - containerPort: 9900
          env:
            - name: KAFKA_URI
              value: kafka-svc:9092
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: dbs-secret
                  key: MONGO_URI
            - name: ELS_URI
              value: "elasticsearch-svc:9200"